server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: amanaje-api
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL}
    username: ${DB_USERNAME:RM561996}
    password: ${DB_PASSWORD:230602}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

amanaje:
  mqtt:
    enabled: ${MQTT_ENABLED:true}
    broker-url: ${MQTT_BROKER_URL:tcp://mqtt-dashboard.com:1883}
    client-id: ${MQTT_CLIENT_ID:amanaje-java-api}
    username: ${MQTT_USERNAME:}
    password: ${MQTT_PASSWORD:}
    telemetry-topic: ${MQTT_TELEMETRY_TOPIC:app/estacoes/+/telemetria}
    status-topic: ${MQTT_STATUS_TOPIC:app/estacoes/+/status}
    command-topic-pattern: ${MQTT_COMMAND_TOPIC_PATTERN:app/estacoes/%s/alertas}
    evaluate-risk-on-message: ${MQTT_EVALUATE_RISK:true}
